// This file was automatically generated.  Do not modify.
/* eslint-disable func-style */
/* eslint-disable require-jsdoc */
/* eslint-disable quote-props */
/* eslint-disable quotes */
/* eslint-disable dot-notation */

function addMsg (Blockly) {

    Object.assign(Blockly.ScratchMsgs.locales["en"],
        {
            "E2BOT_EVENT_CATEGORY": "E2Bot",
            "E2BOT_SETUP": "E2Bot setup",
            "E2BOT_LOOP": "loop",
            //=============================================================
            "E2BOT_MOTOR_CATEGORY": "MotorControl",
            "E2BOT_SET_MOTOR_RUN_FREE": "Set power left %1 right %2",
            "E2BOT_SET_MOTOR_RUN_FORWARD": "Set power %1 run %2 cm",
            "E2BOT_SET_MOTOR_RUN_TURN": "Set power left %1 right %2 turn %3 degrees",
            "E2BOT_SET_MOTOR_RUN_TIME": "Set power left %1 right %2 run %3 sec",
            "E2BOT_SET_MOTOR_RUN_STOP": "Set power stop",
            "E2BOT_SET_MOTOR_SYNC": "Motor sync %1",
            "E2BOT_SET_MOTOR_SYNC_OFF":"off",
            "E2BOT_SET_MOTOR_SYNC_ON":"on",
            "E2BOT_RESET_ENCODER_CM":"Reset %1 counter of cm",
            "E2BOT_RESET_ENCODER_CM_ALL":"all",
            "E2BOT_RESET_ENCODER_CM_AVG":"average",
            "E2BOT_RESET_ENCODER_CM_LEFT":"left",
            "E2BOT_RESET_ENCODER_CM_RIGHT":"right",
            "E2BOT_GET_ENCODER_CM":"get %1 cm",
            "E2BOT_GET_ENCODER_CM_AVG":"average",
            "E2BOT_GET_ENCODER_CM_LEFT":"left",
            "E2BOT_GET_ENCODER_CM_RIGHT":"right",
            "E2BOT_RESET_ENCODER":"Reset %1 counter of degrees",
            "E2BOT_RESET_ENCODER_ALL":"all",
            "E2BOT_RESET_ENCODER_AVG":"average",
            "E2BOT_RESET_ENCODER_LEFT":"left",
            "E2BOT_RESET_ENCODER_RIGHT":"right",
            "E2BOT_GET_ENCODER":"get %1 degrees",
            "E2BOT_GET_ENCODER_AVG":"average",
            "E2BOT_GET_ENCODER_LEFT":"left",
            "E2BOT_GET_ENCODER_RIGHT":"right",
            "E2BOT_GET_SPEED":"get %1 speed",
            "E2BOT_GET_SPEED_AVG":"average",
            "E2BOT_GET_SPEED_LEFT":"left",
            "E2BOT_GET_SPEED_RIGHT":"right",
            //=============================================================
            "E2BOT_OUTPUT_CATEGORY": "Output",
            "E2BOT_SET_BUZZER":"Set buzzer %1 tone %2 sec",
            "E2BOT_SET_BUZZER_B0":"B0",
            "E2BOT_SET_BUZZER_C1":"C1",
            "E2BOT_SET_BUZZER_D1":"D1",
            "E2BOT_SET_BUZZER_E1":"E1",
            "E2BOT_SET_BUZZER_F1":"F1",
            "E2BOT_SET_BUZZER_G1":"G1",
            "E2BOT_SET_BUZZER_A1":"A1",
            "E2BOT_SET_BUZZER_B1":"B1",
            "E2BOT_SET_BUZZER_C2":"C2",
            "E2BOT_SET_BUZZER_D2":"D2",
            "E2BOT_SET_BUZZER_E2":"E2",
            "E2BOT_SET_BUZZER_F2":"F2",
            "E2BOT_SET_BUZZER_G2":"G2",
            "E2BOT_SET_BUZZER_A2":"A2",
            "E2BOT_SET_BUZZER_B2":"B2",
            "E2BOT_SET_BUZZER_C3":"C3",
            "E2BOT_SET_BUZZER_D3":"D3",
            "E2BOT_SET_BUZZER_E3":"E3",
            "E2BOT_SET_BUZZER_F3":"F3",
            "E2BOT_SET_BUZZER_G3":"G3",
            "E2BOT_SET_BUZZER_A3":"A3",
            "E2BOT_SET_BUZZER_B3":"B3",
            "E2BOT_SET_BUZZER_C4":"C4",
            "E2BOT_SET_BUZZER_D4":"D4",
            "E2BOT_SET_BUZZER_E4":"E4",
            "E2BOT_SET_BUZZER_F4":"F4",
            "E2BOT_SET_BUZZER_G4":"G4",
            "E2BOT_SET_BUZZER_A4":"A4",
            "E2BOT_SET_BUZZER_B4":"B4",
            "E2BOT_SET_BUZZER_C5":"C5",
            "E2BOT_SET_BUZZER_D5":"D5",
            "E2BOT_SET_BUZZER_E5":"E5",
            "E2BOT_SET_BUZZER_F5":"F5",
            "E2BOT_SET_BUZZER_G5":"G5",
            "E2BOT_SET_BUZZER_A5":"A5",
            "E2BOT_SET_BUZZER_B5":"B5",
            "E2BOT_SET_BUZZER_C6":"C6",
            "E2BOT_SET_BUZZER_D6":"D6",
            "E2BOT_SET_BUZZER_E6":"E6",
            "E2BOT_SET_BUZZER_F6":"F6",
            "E2BOT_SET_BUZZER_G6":"G6",
            "E2BOT_SET_BUZZER_A6":"A6",
            "E2BOT_SET_BUZZER_B6":"B6",
            "E2BOT_SET_BUZZER_C7":"C7",
            "E2BOT_SET_BUZZER_D7":"D7",
            "E2BOT_SET_BUZZER_E7":"E7",
            "E2BOT_SET_BUZZER_F7":"F7",
            "E2BOT_SET_BUZZER_G7":"G7",
            "E2BOT_SET_BUZZER_A7":"A7",
            "E2BOT_SET_BUZZER_B7":"B7",
            "E2BOT_SET_BUZZER_C8":"C8",
            "E2BOT_SET_BUZZER_D8":"D8",
            "E2BOT_SET_RGB_LED":"Set RGBled red %1 green %2 blue %3",
            //============================================================
            "E2BOT_LCD_CATEGORY":"LCD",
            "E2BOT_SET_LCD_SHOW_WHITE":"white",
            "E2BOT_SET_LCD_SHOW_RED":"red",
            "E2BOT_SET_LCD_SHOW_YELLOW":"yellow",
            "E2BOT_SET_LCD_SHOW_GREEN":"green",
            "E2BOT_SET_LCD_SHOW_INDIGO":"indigo",
            "E2BOT_SET_LCD_SHOW_BLUE":"blue",
            "E2BOT_SET_LCD_SHOW_PURPLE":"purple",
            "E2BOT_SET_LCD_SHOW_BLACK":"black",
            "E2BOT_SET_LCD_SHOW_STR":"Display string %1 at X %2 Y %3 with %4",
            "E2BOT_SET_LCD_SHOW_NUM":"Display number %1 at X %2 Y %3 with %4",
            "E2BOT_SET_LCD_PIXEL":"Display pixel at X %1 Y %2 with %3",
            "E2BOT_SET_LCD_CLEAR":"LCD clear",
            "E2BOT_SET_COLOR_PALETTE":"color palette red %1 green %2 blue %3",
            "E2BOT_SENSOR_TEST_MODE":"Sensor test mode",
            //=============================================================
            "E2BOT_LINESENSOR_CATEGORY": "LineSensor",
            "E2BOT_SET_IR_ONOFF": "Set line sensor %1",
            "E2BOT_SET_IR_ON": "on",
            "E2BOT_SET_IR_OFF": "off",
            "E2BOT_SET_SEARCH_LINE":"Set search %1 line",
            "E2BOT_SET_SEARCH_LINE_WHITE":"white",
            "E2BOT_SET_SEARCH_LINE_BLACK":"black",
            "E2BOT_GET_LINE_POS_IR":"get position of line",
            "E2BOT_GET_LINE_WIDTH_IR":"get width of line",
            "E2BOT_GET_CALIB_IR":"get value %1 of line",
            "E2BOT_GET_ANALOG_IR":"get raw %1 of line",
            "E2BOT_GET_BOOL_IR":"get bool %1 of line",
            "E2BOT_GET_BYTE_IR":"get binary of line",
            "E2BOT_SET_LINE_COLOR_RECODER": "Calibrate line sensor %1 color",
            "E2BOT_SET_LINE_COLOR_RECODER_WHITE":"white",
            "E2BOT_SET_LINE_COLOR_RECODER_BLACK":"black",
            //=============================================================
            "E2BOT_GYROSENSOR_CATEGORY": "GyroSensor",
            "E2BOT_MPU_UPDATA_ONOFF": "Gyro %1",
            "E2BOT_MPU_UPDATA_ON": "on",
            "E2BOT_MPU_UPDATA_OFF": "off",
            "E2BOT_GET_ANG_XYZ": "get %1 axis degree of gyro",
            "E2BOT_GET_ANG_XYZ_Z": "Z",
            "E2BOT_GET_ANG_XYZ_Y": "Y",
            "E2BOT_GET_ANG_XYZ_X": "X",
            "E2BOT_GET_VEL_XYZ": "get %1 axis velocity of gyro",
            "E2BOT_GET_VEL_XYZ_Z": "Z",
            "E2BOT_GET_VEL_XYZ_Y": "Y",
            "E2BOT_GET_VEL_XYZ_X": "X",
            "E2BOT_RESET_MPU": "Reset gyro",
            "E2BOT_CALIBRATE_MPU": "Calibrate gyro sensor %1 sec",
            //=============================================================
            "E2BOT_COLORSENSOR_CATEGORY": "ColorSensor",
            "E2BOT_SET_CSL_ONOFF": "Turn %1 Light of ColoeSensor",
            "E2BOT_SET_CSL_ON": "on",
            "E2BOT_SET_CSL_OFF": "off",
            "E2BOT_COMPARE_COLOR_HUE": "compare color code with %1",
            "E2BOT_COMPARE_COLOR_HUE_RED":"red",
            "E2BOT_COMPARE_COLOR_HUE_YELLOW":"yellow",
            "E2BOT_COMPARE_COLOR_HUE_GREEN":"green",
            "E2BOT_COMPARE_COLOR_HUE_INDIGO":"indigo",
            "E2BOT_COMPARE_COLOR_HUE_BLUE":"blue",
            "E2BOT_COMPARE_COLOR_HUE_PURPLE":"purple",
            "E2BOT_GET_COLOR_HUE":"get color code",
            "E2BOT_GET_COLOR_CALI_RGB": "%1 percentage of color",
            "E2BOT_GET_COLOR_CALI_RGB_RED":"red",
            "E2BOT_GET_COLOR_CALI_RGB_GREEN":"green",
            "E2BOT_GET_COLOR_CALI_RGB_BLUE":"blue",
            "E2BOT_GET_COLOR_RGB": "Get %1 value of color",
            "E2BOT_GET_COLOR_RGB_RED":"red",
            "E2BOT_GET_COLOR_RGB_GREEN":"green",
            "E2BOT_GET_COLOR_RGB_BLUE":"blue",
            //=============================================================
            "E2BOT_VALUESENSOR_CATEGORY": "Sensor(Value)",
            "E2BOT_GET_ULTRASONIC": "get ultrasonic %1",
            "E2BOT_GET_ULTRASONIC_CM": "cm",
            "E2BOT_GET_ULTRASONIC_MM": "mm",
            "E2BOT_GET_LIGHT_SENSOR": "get light sensor",
            "E2BOT_GET_KNOB_SENSOR": "get knob sensor",
            "E2BOT_GET_VOLT_SENSOR": "get voltage sensor",
            "E2BOT_GET_IR_REC": "get IR receive",
            //=============================================================
            "E2BOT_BOOLSENSOR_CATEGORY": "Sensor(Bool)",
            "E2BOT_COMPARE_LIMIT_SENSOR_BUMPED":"Wait limit sensor bumped",
            "E2BOT_COMPARE_LIMIT_SENSOR":"compare limit sensor pressed",
            "E2BOT_COMPARE_TOUCH_SENSOR":"compare touch sensor touched",
            "E2BOT_COMPARE_LR": "compare %1 side sensor",
            "E2BOT_COMPARE_LR_L":"left",
            "E2BOT_COMPARE_LR_R":"right",
            "E2BOT_COMPARE_HALL_SENSOR":"compare hall sensor",
            "E2BOT_COMPARE_HUMAN_SENSOR":"compare human sensor",
            //=============================================================
            "E2BOT_TIMER_CATEGORY": "Timer",
            "E2BOT_RESET_TIMER":"Reset timer %1",
            "E2BOT_RESET_TIMER_1":"1",
            "E2BOT_RESET_TIMER_2":"2",
            "E2BOT_RESET_TIMER_3":"3",
            "E2BOT_RESET_TIMER_4":"4",
            "E2BOT_RESET_TIMER_5":"5",
            "E2BOT_RESET_TIMER_6":"6",
            "E2BOT_RESET_TIMER_7":"7",
            "E2BOT_RESET_TIMER_8":"8",
            "E2BOT_RESET_TIMER_9":"9",
            "E2BOT_RESET_TIMER_10":"10",
            "E2BOT_RESET_TIMER_ALL":"all",
            "E2BOT_GET_TIMER":"get timer %1",
            "E2BOT_GET_TIMER_1":"1",
            "E2BOT_GET_TIMER_2":"2",
            "E2BOT_GET_TIMER_3":"3",
            "E2BOT_GET_TIMER_4":"4",
            "E2BOT_GET_TIMER_5":"5",
            "E2BOT_GET_TIMER_6":"6",
            "E2BOT_GET_TIMER_7":"7",
            "E2BOT_GET_TIMER_8":"8",
            "E2BOT_GET_TIMER_9":"9",
            "E2BOT_GET_TIMER_10":"10",
            //=============================================================
            "E2BOT_ARRAY_CATEGORY": "Array",
            "E2BOT_ARRAY_SETUP":"Set %2 size of array %1",
            "E2BOT_ARRAY_WRITE":"Write %1 at %3 of array %2",
            "E2BOT_ARRAY_READ":"read data from index %2 of array %1",
            //=============================================================
            "E2BOT_MATHTOOLS_CATEGORY": "MathTools",
            "E2BOT_GET_MAX":"max( %1 , %2 )",
            "E2BOT_GET_MIN":"min( %1 , %2 )",
            "E2BOT_GET_MAP":"map %1 from( %2 , %3 ) to ( %4 , %5 )",
            "E2BOT_GET_CONSTRAIN":"constrain %1 between( %2 , %3 )",
            //=============================================================
            "E2BOT_EXPANSION_CATEGORY": "Expansion",
            "E2BOT_SET_SERVO":"Servo %1 move to %2 degrees",
            "E2BOT_SET_SERVO_A0":"A0",
            "E2BOT_SET_SERVO_D2":"D2",
            "E2BOT_SET_MOTOR_EXT":"Expansion motor power %1",
            
        }
    );

    Object.assign(Blockly.ScratchMsgs.locales["zh-cn"],
        {
            "E2BOT_EVENT_CATEGORY": "E2Bot机器人",
            "E2BOT_SETUP": "E2Bot启动初始化",
            "E2BOT_LOOP": "重复执行",
            //=============================================================
            "E2BOT_MOTOR_CATEGORY": "电机控制",
            "E2BOT_SET_MOTOR_RUN_FREE": "动力左 %1 右 %2",
            "E2BOT_SET_MOTOR_RUN_FORWARD": "动力 %1 走 %2 公分",
            "E2BOT_SET_MOTOR_RUN_TURN": "动力左 %1 右 %2 旋转 %3 度",
            "E2BOT_SET_MOTOR_RUN_TIME": "动力左 %1 右 %2 走 %3 秒",
            "E2BOT_SET_MOTOR_RUN_STOP": "动力停止",
            "E2BOT_SET_MOTOR_SYNC": "电机同步 %1",
            "E2BOT_SET_MOTOR_SYNC_OFF":"关闭",
            "E2BOT_SET_MOTOR_SYNC_ON":"开启",
            "E2BOT_RESET_ENCODER_CM":"重置电机 %1 公分计数器",
            "E2BOT_RESET_ENCODER_CM_ALL":"全部",
            "E2BOT_RESET_ENCODER_CM_AVG":"平均",
            "E2BOT_RESET_ENCODER_CM_LEFT":"左边",
            "E2BOT_RESET_ENCODER_CM_RIGHT":"右边",
            "E2BOT_GET_ENCODER_CM":"电机 %1 公分",
            "E2BOT_GET_ENCODER_CM_AVG":"平均",
            "E2BOT_GET_ENCODER_CM_LEFT":"左边",
            "E2BOT_GET_ENCODER_CM_RIGHT":"右边",
            "E2BOT_RESET_ENCODER":"重置电机 %1 角度计数器",
            "E2BOT_RESET_ENCODER_ALL":"全部",
            "E2BOT_RESET_ENCODER_AVG":"平均",
            "E2BOT_RESET_ENCODER_LEFT":"左边",
            "E2BOT_RESET_ENCODER_RIGHT":"右边",
            "E2BOT_GET_ENCODER":"电机 %1 角度",
            "E2BOT_GET_ENCODER_AVG":"平均",
            "E2BOT_GET_ENCODER_LEFT":"左边",
            "E2BOT_GET_ENCODER_RIGHT":"右边",
            "E2BOT_GET_SPEED":"电机 %1 速度",
            "E2BOT_GET_SPEED_AVG":"平均",
            "E2BOT_GET_SPEED_LEFT":"左边",
            "E2BOT_GET_SPEED_RIGHT":"右边",
            //=============================================================
            "E2BOT_OUTPUT_CATEGORY": "输出",
            "E2BOT_SET_BUZZER":"蜂鸣器 %1 音 %2 秒",
            "E2BOT_SET_BUZZER_B0":"B0",
            "E2BOT_SET_BUZZER_C1":"C1",
            "E2BOT_SET_BUZZER_D1":"D1",
            "E2BOT_SET_BUZZER_E1":"E1",
            "E2BOT_SET_BUZZER_F1":"F1",
            "E2BOT_SET_BUZZER_G1":"G1",
            "E2BOT_SET_BUZZER_A1":"A1",
            "E2BOT_SET_BUZZER_B1":"B1",
            "E2BOT_SET_BUZZER_C2":"C2",
            "E2BOT_SET_BUZZER_D2":"D2",
            "E2BOT_SET_BUZZER_E2":"E2",
            "E2BOT_SET_BUZZER_F2":"F2",
            "E2BOT_SET_BUZZER_G2":"G2",
            "E2BOT_SET_BUZZER_A2":"A2",
            "E2BOT_SET_BUZZER_B2":"B2",
            "E2BOT_SET_BUZZER_C3":"C3",
            "E2BOT_SET_BUZZER_D3":"D3",
            "E2BOT_SET_BUZZER_E3":"E3",
            "E2BOT_SET_BUZZER_F3":"F3",
            "E2BOT_SET_BUZZER_G3":"G3",
            "E2BOT_SET_BUZZER_A3":"A3",
            "E2BOT_SET_BUZZER_B3":"B3",
            "E2BOT_SET_BUZZER_C4":"C4",
            "E2BOT_SET_BUZZER_D4":"D4",
            "E2BOT_SET_BUZZER_E4":"E4",
            "E2BOT_SET_BUZZER_F4":"F4",
            "E2BOT_SET_BUZZER_G4":"G4",
            "E2BOT_SET_BUZZER_A4":"A4",
            "E2BOT_SET_BUZZER_B4":"B4",
            "E2BOT_SET_BUZZER_C5":"C5",
            "E2BOT_SET_BUZZER_D5":"D5",
            "E2BOT_SET_BUZZER_E5":"E5",
            "E2BOT_SET_BUZZER_F5":"F5",
            "E2BOT_SET_BUZZER_G5":"G5",
            "E2BOT_SET_BUZZER_A5":"A5",
            "E2BOT_SET_BUZZER_B5":"B5",
            "E2BOT_SET_BUZZER_C6":"C6",
            "E2BOT_SET_BUZZER_D6":"D6",
            "E2BOT_SET_BUZZER_E6":"E6",
            "E2BOT_SET_BUZZER_F6":"F6",
            "E2BOT_SET_BUZZER_G6":"G6",
            "E2BOT_SET_BUZZER_A6":"A6",
            "E2BOT_SET_BUZZER_B6":"B6",
            "E2BOT_SET_BUZZER_C7":"C7",
            "E2BOT_SET_BUZZER_D7":"D7",
            "E2BOT_SET_BUZZER_E7":"E7",
            "E2BOT_SET_BUZZER_F7":"F7",
            "E2BOT_SET_BUZZER_G7":"G7",
            "E2BOT_SET_BUZZER_A7":"A7",
            "E2BOT_SET_BUZZER_B7":"B7",
            "E2BOT_SET_BUZZER_C8":"C8",
            "E2BOT_SET_BUZZER_D8":"D8",
            "E2BOT_SET_RGB_LED":"彩光灯 红 %1 绿 %2 蓝 %3",
            //============================================================
            "E2BOT_LCD_CATEGORY":"LCD显示屏",
            "E2BOT_SET_LCD_SHOW_WHITE":"白色",
            "E2BOT_SET_LCD_SHOW_RED":"红色",
            "E2BOT_SET_LCD_SHOW_YELLOW":"黄色",
            "E2BOT_SET_LCD_SHOW_GREEN":"绿色",
            "E2BOT_SET_LCD_SHOW_INDIGO":"靛色",
            "E2BOT_SET_LCD_SHOW_BLUE":"蓝色",
            "E2BOT_SET_LCD_SHOW_PURPLE":"紫色",
            "E2BOT_SET_LCD_SHOW_BLACK":"黑色",
            "E2BOT_SET_LCD_SHOW_STR":"显示字串 %1 在X座标 %2 Y座标 %3 颜色 %4",
            "E2BOT_SET_LCD_SHOW_NUM":"显示数字 %1 在X座标 %2 Y座标 %3 颜色 %4",
            "E2BOT_SET_LCD_PIXEL":"设定像素点 在X座标 %1 Y座标 %2 颜色 %3",
            "E2BOT_SET_LCD_CLEAR":"显示屏清除",
            "E2BOT_SET_COLOR_PALETTE":"混色器 红 %1 绿 %2 蓝 %3",
            "E2BOT_SENSOR_TEST_MODE":"传感器数据显示模式",
            //=============================================================
            "E2BOT_LINESENSOR_CATEGORY": "循线传感器",
            "E2BOT_SET_IR_ONOFF": "设定循线 %1",
            "E2BOT_SET_IR_ON": "开启",
            "E2BOT_SET_IR_OFF": "关闭",
            "E2BOT_SET_SEARCH_LINE":"设定循 %1",
            "E2BOT_SET_SEARCH_LINE_WHITE":"白线",
            "E2BOT_SET_SEARCH_LINE_BLACK":"黑线",
            "E2BOT_GET_LINE_POS_IR":"循线位置",
            "E2BOT_GET_LINE_WIDTH_IR":"循线宽度",
            "E2BOT_GET_CALIB_IR":"循线第 %1 号数值",
            "E2BOT_GET_ANALOG_IR":"循线第 %1 号原始数值",
            "E2BOT_GET_BOOL_IR":"循线第 %1 号状态",
            "E2BOT_GET_BYTE_IR":"循线二进制值",
            "E2BOT_SET_LINE_COLOR_RECODER": "循线 %1 校正",
            "E2BOT_SET_LINE_COLOR_RECODER_WHITE":"白色",
            "E2BOT_SET_LINE_COLOR_RECODER_BLACK":"黑色",
            //=============================================================
            "E2BOT_GYROSENSOR_CATEGORY": "陀螺仪传感器",
            "E2BOT_MPU_UPDATA_ONOFF": "陀螺仪功能 %1",
            "E2BOT_MPU_UPDATA_ON": "开启",
            "E2BOT_MPU_UPDATA_OFF": "关闭",
            "E2BOT_GET_ANG_XYZ": "陀螺仪 %1 角度",
            "E2BOT_GET_ANG_XYZ_Z": "Z轴",
            "E2BOT_GET_ANG_XYZ_Y": "Y轴",
            "E2BOT_GET_ANG_XYZ_X": "X轴",
            "E2BOT_GET_VEL_XYZ": "陀螺仪 %1 角速度",
            "E2BOT_GET_VEL_XYZ_Z": "Z轴",
            "E2BOT_GET_VEL_XYZ_Y": "Y轴",
            "E2BOT_GET_VEL_XYZ_X": "X轴",
            "E2BOT_RESET_MPU": "陀螺仪重置",
            "E2BOT_CALIBRATE_MPU": "陀螺仪校正 %1 秒",
            //=============================================================
            "E2BOT_COLORSENSOR_CATEGORY": "颜色传感器",
            "E2BOT_SET_CSL_ONOFF": "颜色传感器补光灯 %1",
            "E2BOT_SET_CSL_ON": "开启",
            "E2BOT_SET_CSL_OFF": "关闭",
            "E2BOT_COMPARE_COLOR_HUE": "判断颜色是否为 %1",
            "E2BOT_COMPARE_COLOR_HUE_RED":"红色",
            "E2BOT_COMPARE_COLOR_HUE_YELLOW":"黄色",
            "E2BOT_COMPARE_COLOR_HUE_GREEN":"绿色",
            "E2BOT_COMPARE_COLOR_HUE_INDIGO":"靛色",
            "E2BOT_COMPARE_COLOR_HUE_BLUE":"蓝色",
            "E2BOT_COMPARE_COLOR_HUE_PURPLE":"紫色",
            "E2BOT_GET_COLOR_HUE":"颜色代码",
            "E2BOT_GET_COLOR_CALI_RGB": "颜色中 %1 百分比",
            "E2BOT_GET_COLOR_CALI_RGB_RED":"红色",
            "E2BOT_GET_COLOR_CALI_RGB_GREEN":"绿色",
            "E2BOT_GET_COLOR_CALI_RGB_BLUE":"蓝色",
            "E2BOT_GET_COLOR_RGB": "颜色中 %1 数值",
            "E2BOT_GET_COLOR_RGB_RED":"红色",
            "E2BOT_GET_COLOR_RGB_GREEN":"绿色",
            "E2BOT_GET_COLOR_RGB_BLUE":"蓝色",
            //=============================================================
            "E2BOT_VALUESENSOR_CATEGORY": "传感器(Value)",
            "E2BOT_GET_ULTRASONIC": "超音波 %1 测距",
            "E2BOT_GET_ULTRASONIC_CM": "公分",
            "E2BOT_GET_ULTRASONIC_MM": "公厘",
            "E2BOT_GET_LIGHT_SENSOR": "环境光数值",
            "E2BOT_GET_KNOB_SENSOR": "旋钮数值",
            "E2BOT_GET_VOLT_SENSOR": "电压数值",
            "E2BOT_GET_IR_REC": "接收红外线讯号",
            //=============================================================
            "E2BOT_BOOLSENSOR_CATEGORY": "传感器(Bool)",
            "E2BOT_COMPARE_LIMIT_SENSOR_BUMPED":"等待铁片按钮压放一次",
            "E2BOT_COMPARE_LIMIT_SENSOR":"判断铁片按钮是否压下",
            "E2BOT_COMPARE_TOUCH_SENSOR":"判断触摸板是否触摸",
            "E2BOT_COMPARE_LR": "判断 %1 传感器是否感应",
            "E2BOT_COMPARE_LR_L":"左侧",
            "E2BOT_COMPARE_LR_R":"右侧",
            "E2BOT_COMPARE_HALL_SENSOR":"判断磁场是否感应",
            "E2BOT_COMPARE_HUMAN_SENSOR":"判断移动热源是否感应",
            //=============================================================
            "E2BOT_TIMER_CATEGORY": "计时器",
            "E2BOT_RESET_TIMER":"重置 %1 计时器",
            "E2BOT_RESET_TIMER_1":"1号",
            "E2BOT_RESET_TIMER_2":"2号",
            "E2BOT_RESET_TIMER_3":"3号",
            "E2BOT_RESET_TIMER_4":"4号",
            "E2BOT_RESET_TIMER_5":"5号",
            "E2BOT_RESET_TIMER_6":"6号",
            "E2BOT_RESET_TIMER_7":"7号",
            "E2BOT_RESET_TIMER_8":"8号",
            "E2BOT_RESET_TIMER_9":"9号",
            "E2BOT_RESET_TIMER_10":"10号",
            "E2BOT_RESET_TIMER_ALL":"全部",
            "E2BOT_GET_TIMER":"%1 计时器时间",
            "E2BOT_GET_TIMER_1":"1号",
            "E2BOT_GET_TIMER_2":"2号",
            "E2BOT_GET_TIMER_3":"3号",
            "E2BOT_GET_TIMER_4":"4号",
            "E2BOT_GET_TIMER_5":"5号",
            "E2BOT_GET_TIMER_6":"6号",
            "E2BOT_GET_TIMER_7":"7号",
            "E2BOT_GET_TIMER_8":"8号",
            "E2BOT_GET_TIMER_9":"9号",
            "E2BOT_GET_TIMER_10":"10号",
            //=============================================================
            "E2BOT_ARRAY_CATEGORY": "阵列",
            "E2BOT_ARRAY_SETUP":"设定阵列 %1 长度为 %2",
            "E2BOT_ARRAY_WRITE":"写资料 %1 到阵列 %2 位置 %3",
            "E2BOT_ARRAY_READ":"从阵列 %1 位置 %2 读资料",
            //=============================================================
            "E2BOT_MATHTOOLS_CATEGORY": "运算工具",
            "E2BOT_GET_MAX":"取大值( %1 , %2 )",
            "E2BOT_GET_MIN":"取小值( %1 , %2 )",
            "E2BOT_GET_MAP":"映射 %1 从( %2 , %3 )到( %4 , %5 )",
            "E2BOT_GET_CONSTRAIN":"限制 %1 在( %2 , %3 )之间",
            //=============================================================
            "E2BOT_EXPANSION_CATEGORY": "扩充",
            "E2BOT_SET_SERVO":"伺服电机 %1 定位到 %2 度",
            "E2BOT_SET_SERVO_A0":"A0",
            "E2BOT_SET_SERVO_D2":"D2",
            "E2BOT_SET_MOTOR_EXT":"扩充电机动力 %1 ",
        }
    );

    Object.assign(Blockly.ScratchMsgs.locales["zh-tw"],
        {
            "E2BOT_EVENT_CATEGORY": "E2Bot機器人",
            "E2BOT_SETUP": "E2Bot啟動初始化",
            "E2BOT_LOOP": "重複無限次",
            //=============================================================
            "E2BOT_MOTOR_CATEGORY": "馬達控制",
            "E2BOT_SET_MOTOR_RUN_FREE": "動力左 %1 右 %2",
            "E2BOT_SET_MOTOR_RUN_FORWARD": "動力 %1 走 %2 公分",
            "E2BOT_SET_MOTOR_RUN_TURN": "動力左 %1 右 %2 旋轉 %3 度",
            "E2BOT_SET_MOTOR_RUN_TIME": "動力左 %1 右 %2 走 %3 秒",
            "E2BOT_SET_MOTOR_RUN_STOP": "動力停止",
            "E2BOT_SET_MOTOR_SYNC": "馬達同步 %1",
            "E2BOT_SET_MOTOR_SYNC_OFF":"關閉",
            "E2BOT_SET_MOTOR_SYNC_ON":"開啟",
            "E2BOT_RESET_ENCODER_CM":"重置馬達 %1 公分計數器",
            "E2BOT_RESET_ENCODER_CM_ALL":"全部",
            "E2BOT_RESET_ENCODER_CM_AVG":"平均",
            "E2BOT_RESET_ENCODER_CM_LEFT":"左邊",
            "E2BOT_RESET_ENCODER_CM_RIGHT":"右邊",
            "E2BOT_GET_ENCODER_CM":"馬達 %1 公分",
            "E2BOT_GET_ENCODER_CM_AVG":"平均",
            "E2BOT_GET_ENCODER_CM_LEFT":"左邊",
            "E2BOT_GET_ENCODER_CM_RIGHT":"右邊",
            "E2BOT_RESET_ENCODER":"重置馬達 %1 角度計數器",
            "E2BOT_RESET_ENCODER_ALL":"全部",
            "E2BOT_RESET_ENCODER_AVG":"平均",
            "E2BOT_RESET_ENCODER_LEFT":"左邊",
            "E2BOT_RESET_ENCODER_RIGHT":"右邊",
            "E2BOT_GET_ENCODER":"馬達 %1 角度",
            "E2BOT_GET_ENCODER_AVG":"平均",
            "E2BOT_GET_ENCODER_LEFT":"左邊",
            "E2BOT_GET_ENCODER_RIGHT":"右邊",
            "E2BOT_GET_SPEED":"馬達 %1 速度",
            "E2BOT_GET_SPEED_AVG":"平均",
            "E2BOT_GET_SPEED_LEFT":"左邊",
            "E2BOT_GET_SPEED_RIGHT":"右邊",
            //=============================================================
            "E2BOT_OUTPUT_CATEGORY": "輸出",
            "E2BOT_SET_BUZZER":"蜂鳴器 %1 音 %2 秒",
            "E2BOT_SET_BUZZER_B0":"B0",
            "E2BOT_SET_BUZZER_C1":"C1",
            "E2BOT_SET_BUZZER_D1":"D1",
            "E2BOT_SET_BUZZER_E1":"E1",
            "E2BOT_SET_BUZZER_F1":"F1",
            "E2BOT_SET_BUZZER_G1":"G1",
            "E2BOT_SET_BUZZER_A1":"A1",
            "E2BOT_SET_BUZZER_B1":"B1",
            "E2BOT_SET_BUZZER_C2":"C2",
            "E2BOT_SET_BUZZER_D2":"D2",
            "E2BOT_SET_BUZZER_E2":"E2",
            "E2BOT_SET_BUZZER_F2":"F2",
            "E2BOT_SET_BUZZER_G2":"G2",
            "E2BOT_SET_BUZZER_A2":"A2",
            "E2BOT_SET_BUZZER_B2":"B2",
            "E2BOT_SET_BUZZER_C3":"C3",
            "E2BOT_SET_BUZZER_D3":"D3",
            "E2BOT_SET_BUZZER_E3":"E3",
            "E2BOT_SET_BUZZER_F3":"F3",
            "E2BOT_SET_BUZZER_G3":"G3",
            "E2BOT_SET_BUZZER_A3":"A3",
            "E2BOT_SET_BUZZER_B3":"B3",
            "E2BOT_SET_BUZZER_C4":"C4",
            "E2BOT_SET_BUZZER_D4":"D4",
            "E2BOT_SET_BUZZER_E4":"E4",
            "E2BOT_SET_BUZZER_F4":"F4",
            "E2BOT_SET_BUZZER_G4":"G4",
            "E2BOT_SET_BUZZER_A4":"A4",
            "E2BOT_SET_BUZZER_B4":"B4",
            "E2BOT_SET_BUZZER_C5":"C5",
            "E2BOT_SET_BUZZER_D5":"D5",
            "E2BOT_SET_BUZZER_E5":"E5",
            "E2BOT_SET_BUZZER_F5":"F5",
            "E2BOT_SET_BUZZER_G5":"G5",
            "E2BOT_SET_BUZZER_A5":"A5",
            "E2BOT_SET_BUZZER_B5":"B5",
            "E2BOT_SET_BUZZER_C6":"C6",
            "E2BOT_SET_BUZZER_D6":"D6",
            "E2BOT_SET_BUZZER_E6":"E6",
            "E2BOT_SET_BUZZER_F6":"F6",
            "E2BOT_SET_BUZZER_G6":"G6",
            "E2BOT_SET_BUZZER_A6":"A6",
            "E2BOT_SET_BUZZER_B6":"B6",
            "E2BOT_SET_BUZZER_C7":"C7",
            "E2BOT_SET_BUZZER_D7":"D7",
            "E2BOT_SET_BUZZER_E7":"E7",
            "E2BOT_SET_BUZZER_F7":"F7",
            "E2BOT_SET_BUZZER_G7":"G7",
            "E2BOT_SET_BUZZER_A7":"A7",
            "E2BOT_SET_BUZZER_B7":"B7",
            "E2BOT_SET_BUZZER_C8":"C8",
            "E2BOT_SET_BUZZER_D8":"D8",
            "E2BOT_SET_RGB_LED":"彩光燈 紅 %1 綠 %2 藍 %3",
            //============================================================
            "E2BOT_LCD_CATEGORY":"LCD螢幕",
            "E2BOT_SET_LCD_SHOW_WHITE":"白色",
            "E2BOT_SET_LCD_SHOW_RED":"紅色",
            "E2BOT_SET_LCD_SHOW_YELLOW":"黃色",
            "E2BOT_SET_LCD_SHOW_GREEN":"綠色",
            "E2BOT_SET_LCD_SHOW_INDIGO":"靛色",
            "E2BOT_SET_LCD_SHOW_BLUE":"藍色",
            "E2BOT_SET_LCD_SHOW_PURPLE":"紫色",
            "E2BOT_SET_LCD_SHOW_BLACK":"黑色",
            "E2BOT_SET_LCD_SHOW_STR":"顯示字串 %1 在X座標 %2 Y座標 %3 顏色 %4",
            "E2BOT_SET_LCD_SHOW_NUM":"顯示數字 %1 在X座標 %2 Y座標 %3 顏色 %4",
            "E2BOT_SET_LCD_PIXEL":"設定像素點 在X座標 %1 Y座標 %2 顏色 %3",
            "E2BOT_SET_LCD_CLEAR":"顯示清除",
            "E2BOT_SET_COLOR_PALETTE":"混色器 紅 %1 綠 %2 藍 %3",
            "E2BOT_SENSOR_TEST_MODE":"感測器數據顯示模式",
            //=============================================================
            "E2BOT_LINESENSOR_CATEGORY": "循線感應器",
            "E2BOT_SET_IR_ONOFF": "設定循線 %1",
            "E2BOT_SET_IR_ON": "開啟",
            "E2BOT_SET_IR_OFF": "關閉",
            "E2BOT_SET_SEARCH_LINE":"設定循 %1",
            "E2BOT_SET_SEARCH_LINE_WHITE":"白線",
            "E2BOT_SET_SEARCH_LINE_BLACK":"黑線",
            "E2BOT_GET_LINE_POS_IR":"循線位置",
            "E2BOT_GET_LINE_WIDTH_IR":"循線寬度",
            "E2BOT_GET_CALIB_IR":"循線第 %1 號數值",
            "E2BOT_GET_ANALOG_IR":"循線第 %1 號原始數值",
            "E2BOT_GET_BOOL_IR":"循線第 %1 號狀態",
            "E2BOT_GET_BYTE_IR":"循線二進制值",
            "E2BOT_SET_LINE_COLOR_RECODER": "循線 %1 校正",
            "E2BOT_SET_LINE_COLOR_RECODER_WHITE":"白色",
            "E2BOT_SET_LINE_COLOR_RECODER_BLACK":"黑色",
            //=============================================================
            "E2BOT_GYROSENSOR_CATEGORY": "陀螺儀感應器",
            "E2BOT_MPU_UPDATA_ONOFF": "陀螺儀功能 %1",
            "E2BOT_MPU_UPDATA_ON": "開啟",
            "E2BOT_MPU_UPDATA_OFF": "關閉",
            "E2BOT_GET_ANG_XYZ": "陀螺儀 %1 角度",
            "E2BOT_GET_ANG_XYZ_Z": "Z軸",
            "E2BOT_GET_ANG_XYZ_Y": "Y軸",
            "E2BOT_GET_ANG_XYZ_X": "X軸",
            "E2BOT_GET_VEL_XYZ": "陀螺儀 %1 角速度",
            "E2BOT_GET_VEL_XYZ_Z": "Z軸",
            "E2BOT_GET_VEL_XYZ_Y": "Y軸",
            "E2BOT_GET_VEL_XYZ_X": "X軸",
            "E2BOT_RESET_MPU": "陀螺儀重置",
            "E2BOT_CALIBRATE_MPU": "陀螺儀校正 %1 秒",
            //=============================================================
            "E2BOT_COLORSENSOR_CATEGORY": "顏色感應器",
            "E2BOT_SET_CSL_ONOFF": "顏色感應器補光燈 %1",
            "E2BOT_SET_CSL_ON": "開啟",
            "E2BOT_SET_CSL_OFF": "關閉",
            "E2BOT_COMPARE_COLOR_HUE": "判斷顏色是否為 %1",
            "E2BOT_COMPARE_COLOR_HUE_RED":"紅色",
            "E2BOT_COMPARE_COLOR_HUE_YELLOW":"黃色",
            "E2BOT_COMPARE_COLOR_HUE_GREEN":"綠色",
            "E2BOT_COMPARE_COLOR_HUE_INDIGO":"靛色",
            "E2BOT_COMPARE_COLOR_HUE_BLUE":"藍色",
            "E2BOT_COMPARE_COLOR_HUE_PURPLE":"紫色",
            "E2BOT_GET_COLOR_HUE":"顏色代碼",
            "E2BOT_GET_COLOR_CALI_RGB": "顏色中 %1 百分比",
            "E2BOT_GET_COLOR_CALI_RGB_RED":"紅色",
            "E2BOT_GET_COLOR_CALI_RGB_GREEN":"綠色",
            "E2BOT_GET_COLOR_CALI_RGB_BLUE":"藍色",
            "E2BOT_GET_COLOR_RGB": "顏色中 %1 數值",
            "E2BOT_GET_COLOR_RGB_RED":"紅色",
            "E2BOT_GET_COLOR_RGB_GREEN":"綠色",
            "E2BOT_GET_COLOR_RGB_BLUE":"藍色",
            //=============================================================
            "E2BOT_VALUESENSOR_CATEGORY": "感應器(Value)",
            "E2BOT_GET_ULTRASONIC": "超音波 %1 測距",
            "E2BOT_GET_ULTRASONIC_CM": "公分",
            "E2BOT_GET_ULTRASONIC_MM": "公厘",
            "E2BOT_GET_LIGHT_SENSOR": "環境光數值",
            "E2BOT_GET_KNOB_SENSOR": "旋鈕數值",
            "E2BOT_GET_VOLT_SENSOR": "電壓數值",
            "E2BOT_GET_IR_REC": "接收紅外線訊號",
            //=============================================================
            "E2BOT_BOOLSENSOR_CATEGORY": "感應器(Bool)",
            "E2BOT_COMPARE_LIMIT_SENSOR_BUMPED":"等待鐵片按鈕壓放一次",
            "E2BOT_COMPARE_LIMIT_SENSOR":"判斷鐵片按鈕是否壓下",
            "E2BOT_COMPARE_TOUCH_SENSOR":"判斷觸摸板是否觸摸",
            "E2BOT_COMPARE_LR": "判斷 %1 感應器是否感應",
            "E2BOT_COMPARE_LR_L":"左側",
            "E2BOT_COMPARE_LR_R":"右側",
            "E2BOT_COMPARE_HALL_SENSOR":"判斷磁場是否感應",
            "E2BOT_COMPARE_HUMAN_SENSOR":"判斷移動熱源是否感應",
            //=============================================================
            "E2BOT_TIMER_CATEGORY": "計時器",
            "E2BOT_RESET_TIMER":"重置 %1 計時器",
            "E2BOT_RESET_TIMER_1":"1號",
            "E2BOT_RESET_TIMER_2":"2號",
            "E2BOT_RESET_TIMER_3":"3號",
            "E2BOT_RESET_TIMER_4":"4號",
            "E2BOT_RESET_TIMER_5":"5號",
            "E2BOT_RESET_TIMER_6":"6號",
            "E2BOT_RESET_TIMER_7":"7號",
            "E2BOT_RESET_TIMER_8":"8號",
            "E2BOT_RESET_TIMER_9":"9號",
            "E2BOT_RESET_TIMER_10":"10號",
            "E2BOT_RESET_TIMER_ALL":"全部",
            "E2BOT_GET_TIMER":"%1 計時器時間",
            "E2BOT_GET_TIMER_1":"1號",
            "E2BOT_GET_TIMER_2":"2號",
            "E2BOT_GET_TIMER_3":"3號",
            "E2BOT_GET_TIMER_4":"4號",
            "E2BOT_GET_TIMER_5":"5號",
            "E2BOT_GET_TIMER_6":"6號",
            "E2BOT_GET_TIMER_7":"7號",
            "E2BOT_GET_TIMER_8":"8號",
            "E2BOT_GET_TIMER_9":"9號",
            "E2BOT_GET_TIMER_10":"10號",
            //=============================================================
            "E2BOT_ARRAY_CATEGORY": "陣列",
            "E2BOT_ARRAY_SETUP":"設定陣列 %1 長度為 %2",
            "E2BOT_ARRAY_WRITE":"寫資料 %1 到陣列 %2 位置 %3",
            "E2BOT_ARRAY_READ":"從陣列 %1 位置 %2 讀資料",
            //=============================================================
            "E2BOT_MATHTOOLS_CATEGORY": "運算工具",
            "E2BOT_GET_MAX":"取大值( %1 , %2 )",
            "E2BOT_GET_MIN":"取小值( %1 , %2 )",
            "E2BOT_GET_MAP":"映射 %1 從( %2 , %3 )到( %4 , %5 )",
            "E2BOT_GET_CONSTRAIN":"限制 %1 在( %2 , %3 )之間",
            //=============================================================
            "E2BOT_EXPANSION_CATEGORY": "擴充",
            "E2BOT_SET_SERVO":"伺服馬達 %1 定位到 %2 度",
            "E2BOT_SET_SERVO_A0":"A0",
            "E2BOT_SET_SERVO_D2":"D2",
            "E2BOT_SET_MOTOR_EXT":"擴充馬達動力 %1 ",
            
        }
    );

    return Blockly;
}

exports = addMsg;
// End of combined translations
